---
- name: Jalankan container dari image terbaru
  hosts: docker
  become: true
  tasks:
    - name: Buat Docker network
      community.docker.docker_network:
        name: "{{ docker_network_name }}"
        driver: bridge
      ignore_errors: true 

    - name: Hentikan container lama jika berjalan
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: stopped
      ignore_errors: true  

    - name: Hapus container lama jika ada
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: true 

    - name: Hapus image Docker sebelumnya
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "latest"
        state: absent
      ignore_errors: true 

    - name: Tarik image Docker terbaru
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "latest"
        source: pull

    - name: Jalankan container dengan image baru
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image_name }}:latest"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port }}:{{ container_port }}"
        env:
          DB_HOST: "{{ db_host }}"
          DB_USER: "{{ db_user }}"
          DB_PASS: "{{ db_pass }}"
          DB_NAME: "{{ db_name }}"
        networks:
          - name: "{{ docker_network_name }}"

    - name: Verifikasi container berjalan
      community.docker.docker_container_info:
        name: "{{ container_name }}"
      register: container_info

    - name: Tampilkan informasi container
      ansible.builtin.debug:
        var: container_info
