---
- name: Manage Disk Partition on RHEL
  hosts: "{{ target_host }}"
  become: true
  tasks:
    - name: Check available disk space
      command: lsblk -o NAME,SIZE -b | grep "^{{ disk_name }}"
      register: disk_info
      changed_when: false
      failed_when: false

    - name: Fail if disk does not exist
      fail:
        msg: "Disk {{ disk_name }} not found!"
      when: disk_info.rc != 0

    - name: Get current partition usage
      shell: "lsblk -b -n -o SIZE /dev/{{ disk_name }} | awk '{print $1/1048576}'"
      register: disk_size_mib
      changed_when: false

    - name: Ensure there is enough space for partition
      fail:
        msg: "Not enough space on {{ disk_name }}! Available: {{ disk_size_mib.stdout | int }} MiB, Requested: {{ partition_size_mib }} MiB."
      when: partition_size_mib | int > disk_size_mib.stdout | int

    - name: Create partition if not exists
      shell: >
        echo -e "n\np\n\n\n+{{ partition_size_mib }}M\nw" | fdisk /dev/{{ disk_name }}
      args:
        creates: "/dev/{{ disk_name }}1"

    - name: Reload partition table
      command: partprobe /dev/{{ disk_name }}

    - name: Format partition
      filesystem:
        fstype: "{{ filesystem_type }}"
        dev: "/dev/{{ disk_name }}1"

    - name: Ensure mount point exists
      file:
        path: "{{ mount_point }}"
        state: directory

    - name: Mount partition
      mount:
        path: "{{ mount_point }}"
        src: "/dev/{{ disk_name }}1"
        fstype: "{{ filesystem_type }}"
        state: mounted

    - name: Persist mount in fstab
      lineinfile:
        path: /etc/fstab
        line: "/dev/{{ disk_name }}1 {{ mount_point }} {{ filesystem_type }} defaults 0 0"
        state: present
