- name: Install Docker and Deploy Nginx Container
  hosts: all
  become: yes

  # pre_tasks dijalankan sebelum task utama, cocok untuk setup
  pre_tasks:
    # Blok untuk instalasi pada sistem berbasis RedHat (CentOS, RHEL, dll.)
    - name: Install Docker on RedHat-based systems
      block:
        - name: Install required packages for DNF
          ansible.builtin.yum:
            name: dnf-plugins-core  
            state: present

        - name: Add Docker repository
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/rhel/docker-ce.repo 
            dest: /etc/yum.repos.d/docker-ce.repo

        - name: Install Docker Engine and plugins
          ansible.builtin.yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin   
            state: present
      when: ansible_os_family == "RedHat"
      check_mode: no

    # Blok untuk instalasi pada sistem berbasis Debian (Ubuntu, Debian, dll.)
    - name: Install Docker on Debian-based systems
      block:
        - name: Install required packages for apt
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg-agent
              - software-properties-common
            state: present
            update_cache: yes

        - name: Add Docker GPG key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/trusted.gpg.d/docker.asc
            mode: '0644'
            force: true

        - name: Add Docker repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present

        - name: Install Docker Engine
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: yes
      when: ansible_os_family == "Debian"
      check_mode: no

  # Task utama untuk menjalankan container
  tasks:
    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the Nginx Docker image
      community.docker.docker_image:
        name: nginx
        tag: latest
        source: pull

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx-container
        image: nginx:latest
        state: started
        ports:
          - "9080:80"

    - name: Verify if the container is running
      ansible.builtin.shell: "docker ps | grep nginx-container"
      register: container_status
      changed_when: false # Perintah ini hanya memeriksa, tidak mengubah apa pun
      failed_when: container_status.rc != 0

    - name: Print success message
      ansible.builtin.debug:
        msg: "Nginx container is running and accessible on port 9080."
