---
- name: Setup Apache Web Server with Custom Variables
  hosts: "{{ target_hosts }}"
  become: true
  tasks:
    - name: Install Apache (httpd)
      yum:
        name: httpd
        state: present

    - name: Allow Apache to Bind on Custom Port (SELinux)
      command: semanage port -a -t http_port_t -p tcp {{ apache_port }}
      register: selinux_result
      failed_when: "'already defined' not in selinux_result.stderr and selinux_result.rc != 0"
      ignore_errors: true

    - name: Update Apache to Listen on Custom Port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: 'Listen {{ apache_port }}'

    - name: Open Custom Port in Firewalld
      firewalld:
        port: "{{ apache_port }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      when: ansible_os_family == "RedHat"

    - name: Create Web Page
      copy:
        dest: /var/www/html/index.html
        content: "{{ html_content }}"

    - name: Restart Apache to Apply Changes
      systemd:
        name: httpd
        state: restarted
        enabled: true
